name: Build Documentation
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get mono
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo sh -c 'echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list'
          sudo apt-get update
          sudo apt-get install mono-complete --yes

      - name: Build docs
        run: |
          git lfs version
          git clone https://github.com/FlaxEngine/FlaxEngine.git FlaxEngine
          cd FlaxEngine
          git reset --hard $(cat commit.txt)
          git lfs pull
          ./Development/Scripts/Linux/CallBuildTool.sh -log -arch=x64 -configuration=Development -platform=Windows -buildtargets=FlaxEditor -build -BuildBindingsOnly
          cd ..
          mono docfx/docfx.exe metadata
          mono code2yaml/code2yaml.exe code2yaml.json
          mono docfx/docfx.exe build
          ls _site
          ls _site/api
          ls api-cpp
